apiVersion: v1
kind: Namespace
metadata:
  name: chatbot
  labels:
    name: chatbot
 
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-deployment
  namespace: chatbot
  labels:
    app: chatbot

spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
        
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: sabine-bot
        image: projectreclass/chatbots:latest
        imagePullPolicy: "Always"
        args: ["-preset=Sabine"]
        ports:
        - containerPort: 80
        env:
          - name: CHATBACK_URL
            value: http://3.15.239.232:8000/api/messages

      - name: jose-bot
        image: projectreclass/chatbots:latest
        imagePullPolicy: "Always"
        args: ["-preset=Jose"]
        ports:
        - containerPort: 80
        env:
          - name: CHATBACK_URL
            value: http://3.15.239.232:8000/api/messages

      - name: josiah-bot
        image: projectreclass/chatbots:latest
        imagePullPolicy: "Always"
        args: ["-preset=Josiah"]
        ports:
        - containerPort: 80
        env:
          - name: CHATBACK_URL
            value: http://3.15.239.232:8000/api/messages

